### ISSUE TITLE
Configuration Errors

### ISSUE THREAD

**Issue by qtopie** [anujsharma12feb/cgit-fcgiwrap-nginx#1]
I followed your tutorial step by step, but I got this error  `use: bad interpreter: No such file or directorygi: /usr/bin/perl` in the end. Can you help me out? thanks.

**Comment by qtopie** [comment]
It's not the configuration bug. I reinstall `spawn-fcgi` and everything goes well.

**Comment by anujsharma12feb** [comment]
No issues at all.
I hope my tutorial helped you!!
